# nixpacks.toml
providers = ["python"]

[phases.setup]
nixPkgs = ["gcc"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"